server:
  port: 3344


spring:
  application:
    name: microservices-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Alijing/microservicesConfig.git           # github 上 git 厂库地址
