server:
  port: 8001

spring:
  application:
    name: microservices-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver                  # mysql 驱动包
    url: jdbc:mysql://localhost:3306/microservices-cloud-db3  # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                             # 数据库连接池最小维持连接数
      initial-size: 5                                         # 初始化连接数
      max-total: 5                                            # 最大连接数
      max-wait-millis: 200                                    # 等待连接获取的最大超时时间

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1                                   # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0                               # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/**/*.xml                 # mapper 映射文件

eureka:
  client:                                                     # 将客户端注册进服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservices-dept8003-hystrix               # 自定义 hystrix 相关的服务名称信息
    prefer-ip-address: true                                   # 访问地址可以显示IP地址


info:
  app.name: microservicesCloud
  company.name: www.xxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /


