server:
  port: 9527

spring:
  application:
    name: microservices-zuul-gateway

eureka:
  client:                                                     # 将客户端注册进服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com                             # 自定义 hystrix 相关的服务名称信息
    prefer-ip-address: true                                   # 访问地址可以显示IP地址

info:
  app.name: microservicesCloud
  company.name: www.xxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  ignored-services: "*"                                   #单个写具体微服务名称，多个则用 *
  prefix: /msc
  routes:
    mydept.serviceId: microservices-dept
    mydept.path: /dept/**

